activation: tanh
bnorm: false
drop_out: 0.5
input_dim: 8
nh_layer: 3
nhidden: 200
nz_dim: 32
optimize_out: false
out_dim: 9
output_act: tanh
skip_conn: false
use_huber: false
use_resnet: false
xstat:
- - !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      pHQzktYX2z8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      saFBKtAE1j8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      /B1uU1mu6D8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ogM0tRJ75D8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      yxEoqQkb0z8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      OQn45tXE4z8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      NLO4E8TJ5D8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      phXWoEKI5z8=
- - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      u1smPWYoxz8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      T9WIvotpzj8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      BmzUzWKjyz8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      G579RQGJzj8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      hDJQF4Wwxj8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Vudchk98yj8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      VEsTQzv1zj8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      H9SybzAjyj8=
ystat:
- - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      zPFfvVt3aUA=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ZOG80m7yaEE=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      00TBpglTUEA=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      JwM3plXEgj4=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      GFv9i52JSUA=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      0GFr6al7SkA=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      qxMxQqFQbz8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      nO0qtlZ6Kz8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      f12JqI1zwD8=
- - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      pwFbhUwgYEA=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ib1KLN++b0E=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      NPRHfHqeN0A=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      wrxn3KwUjT4=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      m4cAM+pyKEA=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      bV4pDo2dFEA=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      /AVBo3qbnD8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      oPq3Fq9EKz8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      vjB3E12awT8=
